var BATIMENTS = 
[
  {
    "id": "mairie-annexe",
    "nom": "Mairie Annexe",
    "categorie": "administration",
    "adresse": "Avenue Jean Jaurès, 77164 Ferrières-en-Brie",
    "capacite": "50 personnes",
    "etages": "2 étages",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Salle municipale pour réunions, formations et conseil municipal.",
    "accessibilite": "Accès PMR · Ascenseur · Parking · Transports",
    "equipements": "Wi-Fi · Téléphone · Vidéoprojecteur · Sonorisation · Cuisine · Chauffage",
    "activites": "Réunion / formation / conseil municipal",
    "etat": "RAS",
    "travaux_recents": "N/A",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82157462254268,
    "lng": 2.7045034945885544
  },
  {
    "id": "salle-saint-remy",
    "nom": "Salle Saint-Rémy",
    "categorie": "culture",
    "adresse": "3 Place Auguste Trézy, 77164 Ferrières-en-Brie",
    "capacite": "30 personnes",
    "etages": "N/A",
    "horaires": "Du lundi au dimanche",
    "telephone": "Non communiqué",
    "description": "Salle associative pour activités culturelles. Accueille danse, histoire et arts.",
    "accessibilite": "Accès PMR · Parking",
    "equipements": "Chauffage",
    "activites": "Phenomèn'danse · Lusitanos · Son d'histoire · Cours de Pastel",
    "etat": "Moyen",
    "travaux_recents": "Aucun",
    "travaux_prevus": "Mur",
    "photo": null,
    "lat": 48.82112062643225,
    "lng": 2.7037958312694776
  },
  {
    "id": "salle-fetes",
    "nom": "Salle des Fêtes",
    "categorie": "sport",
    "adresse": "Rue Maryse Bastié, 77164 Ferrières-en-Brie",
    "capacite": "150 personnes",
    "etages": "N/A",
    "horaires": "Du lundi au dimanche",
    "telephone": "Non communiqué",
    "description": "Grande salle polyvalente municipale pour événements et associations.",
    "accessibilite": "Accès PMR · Parking · Transports",
    "equipements": "Wi-Fi (agents) · Vidéoprojecteur · Sonorisation · Cuisine · Chauffage",
    "activites": "ADF · Viet vodao · USDF · Jardin enchanté · École",
    "etat": "Moyen",
    "travaux_recents": "Wi-Fi",
    "travaux_prevus": "En totalité",
    "photo": null,
    "lat": 48.82224738111118,
    "lng": 2.703495604599944
  },
  {
    "id": "modulaire",
    "nom": "Le Modulaire",
    "categorie": "education",
    "adresse": "Place Verdun, 77164 Ferrières-en-Brie",
    "capacite": "20 personnes",
    "etages": "N/A",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Bâtiment modulaire pour réunions et formations.",
    "accessibilite": "Accès PMR · Parking · Transports",
    "equipements": "Sonorisation sur demande · Chauffage",
    "activites": "Réunion / formation - École et syndic",
    "etat": "RAS",
    "travaux_recents": "N/A",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82234738111118,
    "lng": 2.703495604599944
  },
  {
    "id": "salle-trezy",
    "nom": "Salle Auguste Trézy",
    "categorie": "administration",
    "adresse": "Rue Jean Jaurès, 77164 Ferrières-en-Brie",
    "capacite": "30 personnes",
    "etages": "1 étage",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Salle municipale disponible sur demande pour les associations.",
    "accessibilite": "Accès PMR · Ascenseur · Parking · Transports",
    "equipements": "Wi-Fi · Téléphone · Vidéoprojecteur · Sonorisation · Cuisine · Chauffage · Climatisation",
    "activites": "Sur demande",
    "etat": "RAS",
    "travaux_recents": "Cuisine",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82129198504133,
    "lng": 2.7047645063731216
  },
  {
    "id": "salle-mariages",
    "nom": "Salle des Mariages",
    "categorie": "administration",
    "adresse": "Avenue Jean Jaurès, 77164 Ferrières-en-Brie",
    "capacite": "40 personnes",
    "etages": "1 étage",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Salle dédiée aux cérémonies de mariage civil.",
    "accessibilite": "Accès PMR · Ascenseur · Parking",
    "equipements": "Wi-Fi · Téléphone · Sonorisation · Cuisine · Chauffage · Climatisation",
    "activites": "Mariages",
    "etat": "RAS",
    "travaux_recents": "Cuisine",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82129198504133,
    "lng": 2.7047645063731216
  },
  {
    "id": "maison-nature",
    "nom": "Maison de la Nature",
    "categorie": "nature",
    "adresse": "3 Allée du Château, 77164 Ferrières-en-Brie",
    "capacite": "50 personnes",
    "etages": "N/A",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Espace dédié aux manifestations de la communauté Marne et Gondoire.",
    "accessibilite": "Accès PMR · Parking",
    "equipements": "Wi-Fi · Téléphone · Cuisine · Chauffage",
    "activites": "Manifestations Marne et Gondoire",
    "etat": "RAS",
    "travaux_recents": "RAS",
    "travaux_prevus": "RAS",
    "photo": null,
    "lat": 48.81854716539286,
    "lng": 2.721547044824098
  },
  {
    "id": "bulle-tennis",
    "nom": "Bulle de Tennis",
    "categorie": "sport",
    "adresse": "Allée de la Taffarette, 77164 Ferrières-en-Brie",
    "capacite": "4 personnes",
    "etages": "N/A",
    "horaires": "Du lundi au dimanche",
    "telephone": "Non communiqué",
    "description": "Court de tennis couvert utilisé par le Tennis Club.",
    "accessibilite": "Accès PMR · Parking",
    "equipements": "N/A",
    "activites": "Tennis - Tennis Club",
    "etat": "RAS",
    "travaux_recents": "Éclairage LED et serrure",
    "travaux_prevus": "Changement de la bulle",
    "photo": null,
    "lat": 48.819888023494,
    "lng": 2.6949069456523755
  },
  {
    "id": "service-technique",
    "nom": "Service Technique",
    "categorie": "technique",
    "adresse": "1 Rue Charles Cordier / 13 Avenue Paxton, 77164",
    "capacite": "N/A",
    "etages": "1 étage",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Centre technique municipal de la commune.",
    "accessibilite": "Parking · Transports",
    "equipements": "Wi-Fi · Téléphone · Cuisine · Chauffage",
    "activites": "N/A",
    "etat": "RAS / Bon état",
    "travaux_recents": "Cuisine",
    "travaux_prevus": "Éclairage",
    "photo": null,
    "lat": 48.82592639926443,
    "lng": 2.7163507979906174
  },
  {
    "id": "salle-vinci",
    "nom": "Salle Léonard de Vinci",
    "categorie": "education",
    "adresse": "Avenue de Paris, 77164 Ferrières-en-Brie",
    "capacite": "30 personnes",
    "etages": "1 étage",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Salle associative et culturelle pour manifestations officielles.",
    "accessibilite": "Accès PMR · Parking · Transports",
    "equipements": "Téléphone · Sonorisation sur demande · Chauffage",
    "activites": "Ping-pong · Entract · Sons d'histoire · Poker · Manifestations officielles",
    "etat": "RAS",
    "travaux_recents": "Cuisine",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82578342705441,
    "lng": 2.703882512036084
  },
  {
    "id": "kiosque",
    "nom": "Le Kiosque",
    "categorie": "culture",
    "adresse": "Place Auguste Trézy, 77164 Ferrières-en-Brie",
    "capacite": "0 personne",
    "etages": "N/A",
    "horaires": "Du lundi au dimanche",
    "telephone": "Non communiqué",
    "description": "Kiosque municipal utilisé pour le stockage et les événements de pêche.",
    "accessibilite": "Parking",
    "equipements": "Sonorisation sur demande · Chauffage",
    "activites": "Stockage / pêche - Les Amis de la Taffarette",
    "etat": "Moyen",
    "travaux_recents": "Aucun",
    "travaux_prevus": "Aucun",
    "photo": null,
    "lat": 48.82071152305836,
    "lng": 2.7034540782217116
  },
  {
    "id": "lavoir",
    "nom": "Le Lavoir",
    "categorie": "culture",
    "adresse": "Rue Jean Jaurès, 77164 Ferrières-en-Brie",
    "capacite": "N/A",
    "etages": "N/A",
    "horaires": "N/A",
    "telephone": "N/A",
    "description": "Lavoir historique de la commune de Ferrières-en-Brie.",
    "accessibilite": "N/A",
    "equipements": "N/A",
    "activites": "N/A",
    "etat": "N/A",
    "travaux_recents": "N/A",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.822159310761165,
    "lng": 2.699754626238832
  },
  {
    "id": "presbytere",
    "nom": "Salle Presbytère",
    "categorie": "administration",
    "adresse": "2 Place Auguste Trézy, 77164 Ferrières-en-Brie",
    "capacite": "30 personnes",
    "etages": "1 étage",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Salle disponible sur demande pour réunions et formations.",
    "accessibilite": "Accès PMR (RDC) · Parking",
    "equipements": "Wi-Fi · Téléphone · Vidéoprojecteur · Sonorisation · Chauffage",
    "activites": "Réunion / formation",
    "etat": "RAS",
    "travaux_recents": "N/A",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82111040446145,
    "lng": 2.704497749017735
  },
  {
    "id": "ginkgo",
    "nom": "Salle Ginkgo",
    "categorie": "culture",
    "adresse": "3 Rue du Général de Gaulle, 77164 Ferrières-en-Brie",
    "capacite": "30 personnes",
    "etages": "0 étage",
    "horaires": "Du lundi au vendredi",
    "telephone": "Non communiqué",
    "description": "Salle pour activités récréatives et sportives du Ginkgo Club.",
    "accessibilite": "Accès PMR",
    "equipements": "Wi-Fi · Téléphone · Télévision · Sonorisation · Cuisine · Chauffage",
    "activites": "Activités récréatives et sportives - Ginkgo Club",
    "etat": "Vétuste",
    "travaux_recents": "N/A",
    "travaux_prevus": "Ensemble du bâtiment",
    "photo": null,
    "lat": 48.82201482885651,
    "lng": 2.706793154522755
  },
  {
    "id": "appt-urgence",
    "nom": "Maison d'Accueil Provisoire",
    "categorie": "social",
    "adresse": "Rue Jean Jaurès, 77164 Ferrières-en-Brie",
    "capacite": "4 personnes",
    "etages": "1 étage",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Appartement municipal pour hébergement provisoire.",
    "accessibilite": "Parking · Transports",
    "equipements": "Cuisine · Chauffage",
    "activites": "Hébergement provisoire",
    "etat": "N/A",
    "travaux_recents": "N/A",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.821894516339746,
    "lng": 2.703837128674898
  },
  {
    "id": "dojo",
    "nom": "Le Dojo",
    "categorie": "sport",
    "adresse": "396 Route de la Brosse, 77164 Ferrières-en-Brie",
    "capacite": "50 personnes",
    "etages": "0 étage",
    "horaires": "Du lundi au dimanche",
    "telephone": "Non communiqué",
    "description": "Dojo André Pracht, salle de sport municipale.",
    "accessibilite": "Accès PMR · Parking",
    "equipements": "Téléphone · Cuisine · Chauffage · Climatisation",
    "activites": "Sport - École, Judo Club et Pilates",
    "etat": "RAS",
    "travaux_recents": "Pompe à chaleur",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82321853695472,
    "lng": 2.699041197568539
  },
  {
    "id": "meal-repas",
    "nom": "Salle Meal Repas",
    "categorie": "education",
    "adresse": "3 Place Auguste Trézy, 77164 Ferrières-en-Brie",
    "capacite": "N/A",
    "etages": "0 étage",
    "horaires": "Jeudi",
    "telephone": "Non communiqué",
    "description": "Salle utilisée par l'association Meal Repas chaque jeudi.",
    "accessibilite": "Parking · Transports",
    "equipements": "Sonorisation sur demande · Chauffage",
    "activites": "Meal Repas",
    "etat": "Moyen",
    "travaux_recents": "Aucun",
    "travaux_prevus": "Aucun",
    "photo": null,
    "lat": 48.821208526478905,
    "lng": 2.7038969084203717
  },
  {
    "id": "poste",
    "nom": "La Poste",
    "categorie": "service",
    "adresse": "Rue Jean Jaurès, 77164 Ferrières-en-Brie",
    "capacite": "N/A",
    "etages": "1 étage",
    "horaires": "Non communiqué",
    "telephone": "Non communiqué",
    "description": "Bureau de La Poste de Ferrières-en-Brie.",
    "accessibilite": "N/A",
    "equipements": "Téléphone · Cuisine · Chauffage",
    "activites": "La Poste",
    "etat": "N/A",
    "travaux_recents": "N/A",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82096804126956,
    "lng": 2.7056198557389313
  },
  {
    "id": "chateau-eau",
    "nom": "Château d'eau",
    "categorie": "nature",
    "adresse": "Allée du Château d'eau, 77164 Ferrières-en-Brie",
    "capacite": "N/A",
    "etages": "N/A",
    "horaires": "N/A",
    "telephone": "N/A",
    "description": "Château d'eau historique, réserve tampon du réseau municipal.",
    "accessibilite": "N/A",
    "equipements": "N/A",
    "activites": "Réserve tampon",
    "etat": "RAS",
    "travaux_recents": "N/A",
    "travaux_prevus": "N/A",
    "photo": null,
    "lat": 48.82146351197768,
    "lng": 2.7237055348700334
  }
]
;