var MAPTILER_KEY = "AhQ10drEx79exZrx0qNv";

var CATEGORIES = {
  "administration": { label: "Administration", color: "#1A2540", icon: "building-2" },
  "culture":        { label: "Culture",        color: "#1D4ED8", icon: "music" },
  "sport":          { label: "Sport",           color: "#15803D", icon: "dumbbell" },
  "nature":         { label: "Nature",          color: "#4D7C0F", icon: "leaf" },
  "technique":      { label: "Technique",       color: "#475569", icon: "wrench" },
  "social":         { label: "Social",          color: "#B45309", icon: "heart" },
  "infrastructure": { label: "Infrastructure",  color: "#6D28D9", icon: "droplets" }
};

var BATIMENTS = [
  {
    id: "mairie-annexe",
    nom: "Mairie Annexe",
    categorie: "administration",
    adresse: "Ferrières-en-Brie",
    lat: 48.82157462254268,
    lng: 2.7045034945885544,
    photo: null,
    description: "Annexe administrative de la mairie de Ferrières-en-Brie.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "salle-saint-remy",
    nom: "Salle Saint-Rémy",
    categorie: "culture",
    adresse: "Ferrières-en-Brie",
    lat: 48.82112062643225,
    lng: 2.7037958312694776,
    photo: null,
    description: "Salle polyvalente à usage culturel.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "salle-des-fetes",
    nom: "Salle des Fêtes",
    categorie: "culture",
    adresse: "Ferrières-en-Brie",
    lat: 48.82224738111118,
    lng: 2.703495604599944,
    photo: null,
    description: "Salle des fêtes communale.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "modulaire",
    nom: "Modulaire",
    categorie: "technique",
    adresse: "Ferrières-en-Brie",
    lat: 48.82234738111118,
    lng: 2.703595604599944,
    photo: null,
    description: "Bâtiment modulaire communal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "salle-trezy",
    nom: "Salle Auguste Trézy",
    categorie: "culture",
    adresse: "Ferrières-en-Brie",
    lat: 48.82129198504133,
    lng: 2.7047645063731216,
    photo: null,
    description: "Salle polyvalente Auguste Trézy.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "salle-des-mariages",
    nom: "Salle des Mariages",
    categorie: "culture",
    adresse: "Ferrières-en-Brie",
    lat: 48.82129198504133,
    lng: 2.7048645063731216,
    photo: null,
    description: "Salle des mariages — même bâtiment que la Salle Auguste Trézy.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "maison-de-la-nature",
    nom: "Maison de la Nature",
    categorie: "nature",
    adresse: "Ferrières-en-Brie",
    lat: 48.81854716539286,
    lng: 2.7215470448240988,
    photo: null,
    description: "Espace dédié à la sensibilisation environnementale.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "bulle-de-tennis",
    nom: "Bulle de Tennis",
    categorie: "sport",
    adresse: "Ferrières-en-Brie",
    lat: 48.819888023494,
    lng: 2.6949069456523755,
    photo: null,
    description: "Structure gonflable couvrant les terrains de tennis.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "service-technique",
    nom: "Service Technique",
    categorie: "technique",
    adresse: "Ferrières-en-Brie",
    lat: 48.82592639926443,
    lng: 2.7163507979906174,
    photo: null,
    description: "Bâtiment du service technique municipal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "salle-leonard-de-vinci",
    nom: "Salle Léonard de Vinci",
    categorie: "sport",
    adresse: "Ferrières-en-Brie",
    lat: 48.82578342705441,
    lng: 2.70388251203608,
    photo: null,
    description: "Salle sportive et polyvalente Léonard de Vinci.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "kiosque",
    nom: "Le Kiosque",
    categorie: "culture",
    adresse: "Ferrières-en-Brie",
    lat: 48.82071152305836,
    lng: 2.7034540782217116,
    photo: null,
    description: "Kiosque municipal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "lavoir",
    nom: "Le Lavoir",
    categorie: "nature",
    adresse: "Ferrières-en-Brie",
    lat: 48.822159310761165,
    lng: 2.699754626238832,
    photo: null,
    description: "Lavoir ancien du patrimoine communal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "presbytere",
    nom: "Le Presbytère",
    categorie: "administration",
    adresse: "Ferrières-en-Brie",
    lat: 48.82111040446145,
    lng: 2.704497749017735,
    photo: null,
    description: "Presbytère communal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "service-technique-2",
    nom: "Service Technique (STM 2)",
    categorie: "technique",
    adresse: "Ferrières-en-Brie",
    lat: 48.8257513164453,
    lng: 2.7168265000639265,
    photo: null,
    description: "Second site du service technique municipal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "salle-ginkgo",
    nom: "Salle Ginkgo",
    categorie: "social",
    adresse: "Ferrières-en-Brie",
    lat: 48.82201482885651,
    lng: 2.70679315452275,
    photo: null,
    description: "Salle à vocation sociale et associative.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "maison-accueil",
    nom: "Maison d'Accueil Provisoire",
    categorie: "social",
    adresse: "Ferrières-en-Brie",
    lat: 48.821894516339746,
    lng: 2.703837128674898,
    photo: null,
    description: "Structure d'accueil temporaire.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "dojo",
    nom: "Le Dojo",
    categorie: "sport",
    adresse: "Ferrières-en-Brie",
    lat: 48.82321853695472,
    lng: 2.69904119756853,
    photo: null,
    description: "Salle de sport dédiée aux arts martiaux.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "meal-repas",
    nom: "Meal Repas",
    categorie: "social",
    adresse: "Ferrières-en-Brie",
    lat: 48.821208526478905,
    lng: 2.7038969084203717,
    photo: null,
    description: "Espace restauration collective.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "la-poste",
    nom: "La Poste",
    categorie: "administration",
    adresse: "Ferrières-en-Brie",
    lat: 48.82096804126956,
    lng: 2.7056198557389313,
    photo: null,
    description: "Bureau de poste communal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  },
  {
    id: "chateau-eau",
    nom: "Château d'Eau",
    categorie: "infrastructure",
    adresse: "Ferrières-en-Brie",
    lat: 48.82146351197768,
    lng: 2.7237055348700334,
    photo: null,
    description: "Château d'eau du réseau communal.",
    capacite: null,
    pmr: null,
    equipements: null,
    etat: null
  }
];
