var MAPTILER_KEY = "AhQ10drEx79exZrx0qNv";

var CATEGORIES = {
  "administration":    { label: "Administration",    color: "#1E3A5F" },
  "services-mun":      { label: "Services municipaux", color: "#334155" },
  "associations":      { label: "Associations",      color: "#0369A1" },
  "evenements":        { label: "Événements",        color: "#7C3AED" },
  "sport":             { label: "Sport",             color: "#15803D" },
  "culture":           { label: "Culture & Danse",   color: "#1D4ED8" },
  "environnement":     { label: "Environnement",     color: "#4D7C0F" },
  "patrimoine":        { label: "Patrimoine",        color: "#92400E" },
  "ceremonies":        { label: "Cérémonies",        color: "#9D174D" },
  "social":            { label: "Social",            color: "#B45309" },
  "seniors":           { label: "Séniors",           color: "#C2410C" },
  "services-publics":  { label: "Services publics",  color: "#0F766E" },
  "infrastructure":    { label: "Infrastructure",    color: "#6D28D9" }
};

/*
  SOURCE : document officiel "BÂTIMENTS FERRIÈRES-EN-BRIE" (PDF communal).
  GPS   : coordonnées fournies par la commune.
  Données enrichies via collecte directe auprès de la mairie.

  PHOTOS : fichiers dans /photos/<id>.jpeg
  Pour ajouter une photo : déposer le fichier dans /photos/ et renseigner
  le champ photo: "nom-du-fichier.jpeg"
*/

var BATIMENTS = [

  /* ── #1 ─ Salle Rothschild ──────────────────────────────── */
  {
    id: "salle-rothschild",
    nom: "Salle Rothschild",
    categorie: "administration",
    filtres: ["administration"],
    description: "Salle de réunion pour les agents municipaux et salle du conseil municipal. Espace officiel de la commune réservé aux délibérations et réunions internes.",
    public: "Agents municipaux et élus",
    horaires: "Sur réservation uniquement",
    contact: null,
    telephone: null,
    site: null,
    adresse: "Av. Jean Jaurès, Ferrières-en-Brie",
    lat: 48.82157462254268, lng: 2.7045034945885544,
    photo: "salle-rothschild.jpeg",
    capacite: "50 personnes",
    etages: "2 étages",
    pmr: "Oui", ascenseur: "Oui", parking: "Oui", transports: "Oui",
    wifi: "Oui", telephone_equip: "Oui", videoprojecteur: "Oui",
    sonorisation: "Oui", cuisine: "Oui", chauffage: "Oui", climatisation: "Non",
    associations: null,
    activites: "Réunion, formation, conseil municipal",
    evenements: null,
    etat: "RAS",
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #2 ─ Salle Saint-Rémy ──────────────────────────────── */
  {
    id: "salle-saint-remy",
    nom: "Salle Saint-Rémy",
    categorie: "culture",
    filtres: ["culture", "sport", "associations"],
    description: "Salle principalement dédiée à la danse, utilisée par l'association Phenomen'danse. Accueille également les associations Lusitanos, Son d'histoire et les cours de Pastel.",
    public: "Associations et agents municipaux",
    horaires: "Selon le planning des associations",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "3 Place Auguste Trézy, Ferrières-en-Brie",
    lat: 48.82112062643225, lng: 2.7037958312694776,
    photo: "salle-saint-remy.jpeg",
    capacite: "30 personnes",
    etages: null,
    pmr: "Oui", ascenseur: "Non", parking: "Oui", transports: "Non",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: "Non",
    sonorisation: null, cuisine: "Non", chauffage: "Oui", climatisation: "Non",
    associations: "Phenomen'danse, Lusitanos, Son d'histoire, cours de Pastel",
    activites: "Danse, activités associatives",
    evenements: null,
    etat: "Moyen",
    travaux_recents: null,
    travaux_a_prevoir: "Mur"
  },

  /* ── #3 ─ Salle des Fêtes ───────────────────────────────── */
  {
    id: "salle-des-fetes",
    nom: "Salle des Fêtes",
    categorie: "evenements",
    filtres: ["evenements"],
    description: "Grande salle polyvalente de la commune, lieu principal des événements festifs, associatifs et culturels de Ferrières-en-Brie.",
    public: "Associations et événements communaux",
    horaires: "Selon le planning des associations et événements communaux",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "Rue Maryse Bastié, Ferrières-en-Brie",
    lat: 48.82224738111118, lng: 2.703495604599944,
    photo: "salle-des-fetes.jpeg",
    capacite: "150 personnes",
    etages: null,
    pmr: "Oui", ascenseur: "Non", parking: "Oui", transports: "Oui",
    wifi: "Oui (agents uniquement)", telephone_equip: "Non", videoprojecteur: "Oui",
    sonorisation: "Sur demande", cuisine: "Oui", chauffage: "Oui", climatisation: "Non",
    associations: "ADF, Viet Vodao, USDF, Jardin Enchanté, École",
    activites: null,
    evenements: "Événements festifs, culturels et associatifs",
    etat: "Moyen",
    travaux_recents: "Wifi",
    travaux_a_prevoir: "En totalité"
  },

  /* ── #4 ─ Le Modulaire ──────────────────────────────────── */
  {
    id: "modulaire",
    nom: "Le Modulaire",
    categorie: "services-mun",
    filtres: ["services-mun"],
    description: "Bâtiment modulaire dédié aux réunions, utilisé par l'école, le syndic, les agents municipaux et les associations sur demande.",
    public: "École, syndic, agents municipaux, associations sur demande",
    horaires: "Sur réservation uniquement",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "Place Verdun, Ferrières-en-Brie",
    lat: 48.82234738111118, lng: 2.703595604599944,
    photo: "modulaire.jpeg",
    capacite: "20 personnes",
    etages: null,
    pmr: "Oui", ascenseur: "Non", parking: "Oui", transports: "Oui",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: "Non",
    sonorisation: "Sur demande", cuisine: "Non", chauffage: "Oui", climatisation: "Non",
    associations: "École, syndic",
    activites: "Réunion, formation",
    evenements: null,
    etat: "RAS",
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #5 ─ Salle Trézy ───────────────────────────────────── */
  {
    id: "salle-trezy",
    nom: "Salle Trézy",
    categorie: "services-mun",
    filtres: ["services-mun"],
    description: "Salle de réunion polyvalente destinée aux associations et aux agents municipaux. Entièrement équipée pour les réunions et formations.",
    public: "Associations et agents municipaux",
    horaires: "Sur réservation obligatoire",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "Rue Jean Jaurès, Ferrières-en-Brie",
    lat: 48.82129198504133, lng: 2.7047645063731216,
    photo: "salle-trezy.jpeg",
    capacite: "30 personnes",
    etages: "1 étage",
    pmr: "Oui", ascenseur: "Oui", parking: "Oui", transports: "Oui",
    wifi: "Oui", telephone_equip: "Oui", videoprojecteur: "Oui",
    sonorisation: "Sur demande", cuisine: "Oui", chauffage: "Oui", climatisation: "Oui",
    associations: "Sur demande",
    activites: "Réunion, formation",
    evenements: null,
    etat: "RAS",
    travaux_recents: "Cuisine",
    travaux_a_prevoir: null
  },

  /* ── #6 ─ Salle des Mariages ────────────────────────────── */
  {
    id: "salle-des-mariages",
    nom: "Salle des Mariages",
    categorie: "ceremonies",
    filtres: ["ceremonies", "services-mun"],
    description: "Lieu officiel des cérémonies de mariage civil et des événements officiels de la commune de Ferrières-en-Brie.",
    public: "Futurs mariés, invités et événements officiels de la commune",
    horaires: "Uniquement lors des cérémonies officielles",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "Av. Jean Jaurès, Ferrières-en-Brie",
    lat: 48.82139198504133, lng: 2.7048645063731216,
    photo: "salle-des-mariages.jpeg",
    capacite: "40 personnes",
    etages: "1 étage",
    pmr: "Oui", ascenseur: "Oui", parking: "Oui", transports: "Non",
    wifi: "Oui", telephone_equip: "Oui", videoprojecteur: "Non",
    sonorisation: "Oui", cuisine: "Oui", chauffage: "Oui", climatisation: "Oui",
    associations: null,
    activites: "Mariages civils, événements officiels",
    evenements: null,
    etat: "RAS",
    travaux_recents: "Cuisine",
    travaux_a_prevoir: null
  },

  /* ── #7 ─ Maison de la Nature ───────────────────────────── */
  {
    id: "maison-de-la-nature",
    nom: "Maison de la Nature",
    categorie: "environnement",
    filtres: ["environnement"],
    description: "Espace dédié aux événements liés à l'environnement, géré par l'intercommunalité Marne et Gondoire. Lieu de sensibilisation et de découverte de la nature pour le grand public, les scolaires et les associations.",
    public: "Grand public, scolaires et associations",
    horaires: "Lors des événements organisés par Marne et Gondoire",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "3 Allée du Château, Ferrières-en-Brie",
    lat: 48.81854716539286, lng: 2.721547044824098,
    photo: "maison-de-la-nature.jpeg",
    capacite: "50 personnes",
    etages: null,
    pmr: "Oui", ascenseur: "Non", parking: "Oui", transports: "Non",
    wifi: "Oui", telephone_equip: "Oui", videoprojecteur: "Non",
    sonorisation: null, cuisine: "Oui", chauffage: "Oui", climatisation: null,
    associations: null,
    activites: "Sensibilisation à l'environnement",
    evenements: "Manifestations Marne et Gondoire",
    etat: "RAS",
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #8 ─ Bulle de Tennis ───────────────────────────────── */
  {
    id: "bulle-de-tennis",
    nom: "Bulle de Tennis",
    categorie: "sport",
    filtres: ["sport"],
    description: "Structure gonflable couvrant les terrains de tennis du Tennis Club, permettant la pratique toute l'année quelle que soit la météo.",
    public: "Membres du Tennis Club uniquement",
    horaires: "Selon le planning du Tennis Club",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: "https://ferrieres-en-brie.com/les-associations-de-ferrieres-en-brie/",
    adresse: "Allée de la Taffarette, Ferrières-en-Brie",
    lat: 48.819888023494, lng: 2.6949069456523755,
    photo: "bulle-de-tennis.jpeg",
    capacite: "4 personnes par court",
    etages: null,
    pmr: "Oui", ascenseur: "Non", parking: "Oui", transports: "Non",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: "Non",
    sonorisation: "Non", cuisine: "Non", chauffage: "Non", climatisation: "Non",
    associations: "Tennis Club",
    activites: "Tennis",
    evenements: null,
    etat: "RAS",
    travaux_recents: "Éclairage LED et serrure",
    travaux_a_prevoir: "Changement de la bulle"
  },

  /* ── #9 ─ Service Technique CTM1 ────────────────────────── */
  {
    id: "service-technique-ctm1",
    nom: "Service Technique (CTM1)",
    categorie: "services-mun",
    filtres: ["services-mun"],
    description: "Site principal du service technique municipal. Lieu d'approvisionnement, de stockage et de logistique pour les agents de la commune.",
    public: "Agents municipaux uniquement",
    horaires: "Réservé aux agents municipaux",
    contact: null,
    telephone: null,
    site: null,
    adresse: "1 rue Charles Cordier, Ferrières-en-Brie",
    lat: 48.82592639926443, lng: 2.7163507979906174,
    photo: "service-technique-ctm1.jpeg",
    capacite: null,
    etages: "1 étage",
    pmr: "Non", ascenseur: "Non", parking: "Oui", transports: "Oui",
    wifi: "Oui", telephone_equip: "Oui", videoprojecteur: "Non",
    sonorisation: "Non", cuisine: "Oui", chauffage: "Oui", climatisation: "Non",
    associations: null,
    activites: "Approvisionnement, stockage, logistique",
    evenements: null,
    etat: "RAS",
    travaux_recents: "Cuisine",
    travaux_a_prevoir: "Éclairage"
  },

  /* ── #10 ─ Salle Léonard de Vinci ───────────────────────── */
  {
    id: "salle-leonard",
    nom: "Salle Léonard de Vinci",
    categorie: "associations",
    filtres: ["associations", "evenements"],
    description: "Salle polyvalente accueillant le ping-pong, les jeux de rôle, jeux de plateau, théâtre, poker et les événements municipaux officiels.",
    public: "Associations et événements communaux",
    horaires: "Selon le planning des associations",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "Av. de Paris, Ferrières-en-Brie",
    lat: 48.82578342705441, lng: 2.703882512036084,
    photo: "salle-leonard.jpeg",
    capacite: "30 personnes",
    etages: "1 étage",
    pmr: "Oui", ascenseur: "Non", parking: "Oui", transports: "Oui",
    wifi: "Non", telephone_equip: "Oui", videoprojecteur: "Non",
    sonorisation: "Sur demande", cuisine: "Non", chauffage: "Oui", climatisation: "Non",
    associations: "Ping-pong, Ours Hibou, Entract, Sons d'histoire, Poker",
    activites: "Ping-pong, jeux de rôle, jeux de plateau, théâtre, poker",
    evenements: "Manifestations officielles",
    etat: "RAS",
    travaux_recents: "Cuisine",
    travaux_a_prevoir: null
  },

  /* ── #11 ─ Le Kiosque ───────────────────────────────────── */
  {
    id: "kiosque",
    nom: "Le Kiosque",
    categorie: "associations",
    filtres: ["associations", "services-mun"],
    description: "Espace de stockage utilisé par l'association Les Amis de la Taffarette pour le matériel de pêche.",
    public: "Association Les Amis de la Taffarette et agents municipaux",
    horaires: "Selon les besoins de l'association",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "Place Auguste Trézy, Ferrières-en-Brie",
    lat: 48.82071152305836, lng: 2.7034540782217116,
    photo: "kiosque.jpeg",
    capacite: null,
    etages: null,
    pmr: "Non", ascenseur: "Non", parking: "Oui", transports: "Non",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: "Non",
    sonorisation: "Sur demande", cuisine: "Non", chauffage: "Oui", climatisation: "Non",
    associations: "Les Amis de la Taffarette",
    activites: "Stockage matériel de pêche",
    evenements: null,
    etat: "Moyen",
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #12 ─ Le Lavoir ────────────────────────────────────── */
  {
    id: "lavoir",
    nom: "Le Lavoir",
    categorie: "patrimoine",
    filtres: ["patrimoine"],
    description: "Lavoir ancien classé au patrimoine communal, témoin de l'architecture rurale et de l'histoire de Ferrières-en-Brie. Accessible sur demande uniquement.",
    public: "Visiteurs et curieux sur demande",
    horaires: "Accès sur demande",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "Rue Jean Jaurès, Ferrières-en-Brie",
    lat: 48.82027216253771, lng: 2.7060607527097678,
    photo: "lavoir.jpeg",
    capacite: null,
    etages: null,
    pmr: "Non", ascenseur: null, parking: "Non", transports: "Non",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: null,
    sonorisation: null, cuisine: "Non", chauffage: "Non", climatisation: "Non",
    associations: null,
    activites: "Patrimoine, visites",
    evenements: null,
    etat: null,
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #13 ─ Le Presbytère ────────────────────────────────── */
  {
    id: "presbytere",
    nom: "Le Presbytère",
    categorie: "services-mun",
    filtres: ["services-mun", "associations"],
    description: "Salle de réunion mise à disposition des associations et des agents municipaux de la commune.",
    public: "Associations et agents municipaux",
    horaires: "Sur réservation",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "2 Pl. Auguste Trézy, Ferrières-en-Brie",
    lat: 48.82111040446145, lng: 2.704497749017735,
    photo: "presbytere.jpeg",
    capacite: "30 personnes",
    etages: "1 étage",
    pmr: "Oui (RDC)", ascenseur: "Non", parking: "Oui", transports: "Non",
    wifi: "Oui", telephone_equip: "Oui", videoprojecteur: "Oui",
    sonorisation: "Sur demande", cuisine: "Non", chauffage: "Oui", climatisation: "Non",
    associations: "Sur demande",
    activites: "Réunion, formation",
    evenements: null,
    etat: "RAS",
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #14 ─ Service Technique CTM2 ───────────────────────── */
  {
    id: "service-technique-ctm2",
    nom: "Service Technique (CTM2)",
    categorie: "services-mun",
    filtres: ["services-mun"],
    description: "Second site du service technique municipal. Lieu d'approvisionnement, de stockage et de logistique pour les agents de la commune, complémentaire au CTM1.",
    public: "Agents municipaux uniquement",
    horaires: "Réservé aux agents municipaux",
    contact: null,
    telephone: null,
    site: null,
    adresse: "13 avenue Paxton, Ferrières-en-Brie",
    lat: 48.8257513164453, lng: 2.7168265000639265,
    photo: "service-technique-ctm2.jpeg",
    capacite: null,
    etages: "1 étage",
    pmr: "Non", ascenseur: "Non", parking: "Oui", transports: "Oui",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: "Non",
    sonorisation: "Non", cuisine: "Non", chauffage: "Non", climatisation: "Non",
    associations: null,
    activites: "Approvisionnement, stockage, logistique",
    evenements: null,
    etat: "Bon état",
    travaux_recents: null,
    travaux_a_prevoir: "Éclairage"
  },

  /* ── #15 ─ Salle Ginkgo ─────────────────────────────────── */
  {
    id: "salle-ginkgo",
    nom: "Salle Ginkgo",
    categorie: "seniors",
    filtres: ["seniors", "associations"],
    description: "Espace de loisirs et d'activités récréatives destiné principalement aux personnes âgées, avec une dimension intergénérationnelle. Géré par le Ginkgo Club.",
    public: "Membres du Ginkgo Club uniquement",
    horaires: "Selon les activités du Ginkgo Club, du lundi au vendredi",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "3 Rue du Général de Gaulle, Ferrières-en-Brie",
    lat: 48.82201482885651, lng: 2.706793154522755,
    photo: "salle-ginkgo.jpeg",
    capacite: "30 personnes",
    etages: null,
    pmr: "Oui", ascenseur: "Non", parking: "Non", transports: "Non",
    wifi: "Oui", telephone_equip: "Oui", videoprojecteur: "Télévision",
    sonorisation: "Sur demande", cuisine: "Oui", chauffage: "Oui", climatisation: "Non",
    associations: "Ginkgo Club",
    activites: "Loisirs, activités récréatives, intergénérationnel",
    evenements: null,
    etat: "Vétuste",
    travaux_recents: null,
    travaux_a_prevoir: "L'ensemble"
  },

  /* ── #16 ─ Maison d'Accueil Provisoire ──────────────────── */
  {
    id: "maison-accueil",
    nom: "Maison d'Accueil Provisoire",
    categorie: "social",
    filtres: ["social"],
    description: "Logement d'urgence mis à disposition par la commune pour accueillir temporairement des familles en difficulté ou en situation de crise.",
    public: "Familles en situation d'urgence, sur décision de la mairie",
    horaires: "Sur décision de la mairie uniquement",
    contact: null,
    telephone: null,
    site: null,
    adresse: "Rue Jean Jaurès, Ferrières-en-Brie",
    lat: 48.821894516339746, lng: 2.703837128674898,
    photo: "maison-accueil.jpeg",
    capacite: "4 personnes",
    etages: "1 étage",
    pmr: "Non", ascenseur: "Non", parking: "Oui", transports: "Oui",
    wifi: null, telephone_equip: null, videoprojecteur: null,
    sonorisation: null, cuisine: "Oui", chauffage: "Oui", climatisation: "Non",
    associations: null,
    activites: "Hébergement d'urgence",
    evenements: null,
    etat: null,
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #17 ─ Le Dojo ──────────────────────────────────────── */
  {
    id: "dojo",
    nom: "Le Dojo",
    categorie: "sport",
    filtres: ["sport"],
    description: "Salle de sport dédiée aux arts martiaux et disciplines associées. Utilisée par le Judo Club, l'école et les cours de Pilates.",
    public: "Associations et scolaires",
    horaires: "Selon le planning des associations",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "396 route de la Brosse, Ferrières-en-Brie",
    lat: 48.82321853695472, lng: 2.699041197568539,
    photo: "dojo.jpeg",
    capacite: "50 personnes",
    etages: null,
    pmr: "Oui", ascenseur: "Non", parking: "Oui", transports: "Non",
    wifi: "Non", telephone_equip: "Oui", videoprojecteur: "Non",
    sonorisation: "Non", cuisine: "Oui", chauffage: "Oui", climatisation: "Oui",
    associations: "Judo Club, Pilates, École",
    activites: "Arts martiaux, judo, pilates, sports",
    evenements: null,
    etat: "RAS",
    travaux_recents: "Pompe à chaleur",
    travaux_a_prevoir: null
  },

  /* ── #18 ─ Salle Meal Repas ─────────────────────────────── */
  {
    id: "meal-repas",
    nom: "Salle Meal Repas",
    categorie: "social",
    filtres: ["social", "associations"],
    description: "Espace dédié à la distribution d'aide alimentaire par l'association Meal Repas. Ouvert chaque jeudi aux bénéficiaires et bénévoles de l'association.",
    public: "Bénéficiaires et bénévoles de l'association Meal Repas",
    horaires: "Jeudi uniquement",
    contact: "associations@ferrieresenbrie.fr",
    telephone: null,
    site: null,
    adresse: "3 Place Auguste Trézy, Ferrières-en-Brie",
    lat: 48.821208526478905, lng: 2.7038969084203717,
    photo: "meal-repas.jpeg",
    capacite: null,
    etages: null,
    pmr: "Non", ascenseur: "Non", parking: "Oui", transports: "Oui",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: "Non",
    sonorisation: "Sur demande", cuisine: "Non", chauffage: "Oui", climatisation: "Non",
    associations: "Meal Repas",
    activites: "Distribution d'aide alimentaire",
    evenements: null,
    etat: "Moyen",
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #19 ─ La Poste ─────────────────────────────────────── */
  {
    id: "la-poste",
    nom: "La Poste",
    categorie: "services-publics",
    filtres: ["services-publics"],
    description: "Bureau de poste de proximité offrant les services postaux et financiers aux habitants de Ferrières-en-Brie.",
    public: "Tout public",
    horaires: "Mar, Mer, Ven : 13h30–16h30 · Sam : 09h00–12h00 · Lun, Dim : Fermé",
    contact: null,
    telephone: "09 70 82 36 31",
    site: null,
    adresse: "Rue Jean Jaurès, Ferrières-en-Brie",
    lat: 48.82096804126956, lng: 2.7056198557389313,
    photo: "la-poste.jpeg",
    capacite: null,
    etages: "1 étage",
    pmr: "Non", ascenseur: null, parking: "Non", transports: "Non",
    wifi: null, telephone_equip: "Oui", videoprojecteur: null,
    sonorisation: null, cuisine: "Oui", chauffage: "Oui", climatisation: null,
    associations: null,
    activites: "Services postaux et financiers",
    evenements: null,
    etat: null,
    travaux_recents: null,
    travaux_a_prevoir: null
  },

  /* ── #20 ─ Château d'Eau ────────────────────────────────── */
  {
    id: "chateau-eau",
    nom: "Château d'Eau",
    categorie: "infrastructure",
    filtres: ["infrastructure"],
    description: "Infrastructure technique du réseau d'eau communal, toujours en fonction et protégée. Non accessible au public. Présente une valeur patrimoniale notable dans le paysage de Ferrières-en-Brie.",
    public: "Agents municipaux uniquement",
    horaires: "Non accessible au public",
    contact: null,
    telephone: null,
    site: null,
    adresse: "Allée du Château d'eau, Ferrières-en-Brie",
    lat: 48.82146351197768, lng: 2.7237055348700334,
    photo: "chateau-eau.jpeg",
    capacite: null,
    etages: null,
    pmr: "Non", ascenseur: "Non", parking: "Non", transports: "Non",
    wifi: "Non", telephone_equip: "Non", videoprojecteur: null,
    sonorisation: null, cuisine: null, chauffage: null, climatisation: null,
    associations: null,
    activites: "Infrastructure eau potable, réserve tampon",
    evenements: null,
    etat: "RAS",
    travaux_recents: null,
    travaux_a_prevoir: null
  }

];
